# Generated by Django 5.2.15 on 2026-07-03 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Corpo')),
                ('source_url', models.URLField(max_length=2000, verbose_name='URL da Fonte')),
                ('source_name', models.CharField(max_length=100, verbose_name='Nome da Fonte')),
                ('sentiment', models.CharField(choices=[('BULLISH', 'Alta'), ('BEARISH', 'Baixa'), ('NEUTRAL', 'Neutro')], default='NEUTRAL', max_length=10, verbose_name='Sentimento')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Pontuação de Sentimento')),
                ('published_at', models.DateTimeField(verbose_name='Publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='market_data.asset', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Artigo de Notícia',
                'verbose_name_plural': 'Artigos de Notícias',
                'ordering': ['-published_at'],
            },
        ),
    ]
