# Generated by Django 5.2.15 on 2026-07-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('source', models.CharField(max_length=100, verbose_name='Fonte')),
                ('reference_date', models.DateField(verbose_name='Data de Referência')),
                ('value', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Valor')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Indicador Macro',
                'verbose_name_plural': 'Indicadores Macro',
                'ordering': ['name', '-reference_date'],
                'unique_together': {('name', 'reference_date')},
            },
        ),
    ]
