# Generated by Django 5.2.15 on 2026-07-03 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True, verbose_name='Ticker')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('asset_type', models.CharField(choices=[('FUTURE', 'Futuro'), ('STOCK', 'Ação')], max_length=10, verbose_name='Tipo de Ativo')),
                ('exchange', models.CharField(default='B3', max_length=20, verbose_name='Bolsa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='OHLCCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=10, verbose_name='Timeframe')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('open', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Abertura')),
                ('high', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Máxima')),
                ('low', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Mínima')),
                ('close', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Fechamento')),
                ('volume', models.BigIntegerField(verbose_name='Volume')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market_data.asset', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Candle OHLC',
                'verbose_name_plural': 'Candles OHLC',
                'ordering': ['asset', 'timeframe', 'timestamp'],
                'unique_together': {('asset', 'timestamp', 'timeframe')},
            },
        ),
    ]
