# Generated by Django 5.2.15 on 2026-07-03 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atr_value', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Valor ATR')),
                ('suggested_stop_loss', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Stop Loss Sugerido')),
                ('user_capital', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Capital do Usuário (R$)')),
                ('position_size', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Tamanho da Posição')),
                ('kelly_fraction', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Fração de Kelly')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_calculations', to='market_data.asset', verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cálculo de Risco',
                'verbose_name_plural': 'Cálculos de Risco',
                'ordering': ['-created_at'],
            },
        ),
    ]
