"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Django Channels — suporte a WebSocket / ASGI (Tarefa 7.1.1)
    'channels',

    'dashboard',
    'accounts',
    'analysis',
    'ai_agents',
    'backtest',
    'fundamentals',
    'market_data',
    'news',
    'risk',
    'watchlist',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth – redirecionamentos
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Allauth – configurações de conta
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Django Allauth – obrigatório nas versões modernas
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ─────────────────────────────────────────────────────────────────────────────
# Django Channels — ASGI e WebSocket (Tarefa 7.1.1)
# ─────────────────────────────────────────────────────────────────────────────

# Aponta para o roteador ASGI definido em core/asgi.py
ASGI_APPLICATION = 'core.asgi.application'

# Channel Layers — backend Redis (produção) ou InMemory (desenvolvimento)
# Em desenvolvimento (DEBUG=True), usa InMemoryChannelLayer para evitar
# dependência de Redis local. Em produção, usa channels_redis com Redis.
if DEBUG:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [config('REDIS_URL', default='redis://localhost:6379/0')],
            },
        },
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LLM Configuration
LLM_PROVIDER = config('LLM_PROVIDER', default='google')
LLM_API_KEY = config('LLM_API_KEY', default='')

# Redis
REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')


# ─────────────────────────────────────────────────────────────────────────────
# Cache — Django cache framework com backend Redis (Tarefa 6.7.1)
# ─────────────────────────────────────────────────────────────────────────────

# Cache — LocMem em desenvolvimento (sem Redis), Redis em produção (Tarefa 6.7.1).
_REDIS_CACHE_URL = config('REDIS_CACHE_URL', default='redis://localhost:6379/1')

if DEBUG:
    # Sem dependência de Redis em dev — cache em memória do processo
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'trade-intel-dev',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_CACHE_URL,
            'OPTIONS': {
                'db': '1',
            },
            'KEY_PREFIX': 'trade_intel',
            'TIMEOUT': 300,
        }
    }


# ─────────────────────────────────────────────────────────────────────────────
# Celery — Configuração (Tarefas 4.1.3 e 4.1.4)
# ─────────────────────────────────────────────────────────────────────────────

# 4.1.3 — Broker e result backend via Redis
CELERY_BROKER_URL = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://localhost:6379/0')

# Fuso horário alinhado ao Django
CELERY_TIMEZONE = 'America/Sao_Paulo'

# Serialização JSON para compatibilidade e segurança
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Acknowledge task apenas após conclusão (evita perda de tasks em crash do worker)
CELERY_TASK_ACKS_LATE = True

# Prefetch de 1 task por worker — melhor distribuição de carga para tasks longas
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# 4.1.4 — Celery Beat Schedule: 5 tasks agendadas conforme o PRD
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    # Task 4.2.1 — Coleta intraday OHLC (1 min, apenas em horário de pregão)
    # Pregão B3: seg–sex 09:00–18:00 (América/São Paulo)
    'fetch-intraday-ohlc-every-1min': {
        'task': 'market_data.tasks.fetch_intraday_ohlc',
        'schedule': 60,  # segundos
        'options': {'expires': 55},  # descarta se worker estiver atrasado
    },

    # Task 4.2.2 — Coleta diária OHLC via yfinance (a cada 1h no pregão)
    'fetch-daily-ohlc-every-1h': {
        'task': 'market_data.tasks.fetch_daily_ohlc',
        'schedule': crontab(minute=0, hour='9-18', day_of_week='1-5'),
    },

    # Task 4.5.1 — Dados macro BCB: SELIC e IPCA (a cada 2h)
    'fetch-macro-data-every-2h': {
        'task': 'news.tasks.fetch_macro_data',
        'schedule': crontab(minute=0, hour='*/2'),
    },

    # Task 4.3.1 — Fundamentus scraping (uma vez por dia às 07:00)
    'fetch-fundamentals-daily': {
        'task': 'fundamentals.tasks.fetch_fundamentals',
        'schedule': crontab(minute=0, hour=7),
    },

    # Task 4.4.1 — Coleta de notícias (uma vez por dia às 06:30)
    'fetch-news-daily': {
        'task': 'news.tasks.fetch_news',
        'schedule': crontab(minute=30, hour=6),
    },

    # 7.4.5 — Verifica alertas de preço a cada 1 minuto
    'check-price-alerts-every-1min': {
        'task': 'watchlist.tasks.check_price_alerts',
        'schedule': 60,  # segundos
        'options': {'expires': 55},  # descarta se worker estiver atrasado
    },
}
