# Generated by Django 5.2.15 on 2026-07-03 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(verbose_name='Data de Referência')),
                ('pl_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P/L')),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='ROE (%)')),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Dividend Yield (%)')),
                ('ev_ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EV/EBITDA')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Dados Brutos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamental_data', to='market_data.asset', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Dado Fundamentalista',
                'verbose_name_plural': 'Dados Fundamentalistas',
                'ordering': ['asset', '-reference_date'],
                'unique_together': {('asset', 'reference_date')},
            },
        ),
    ]
