# Generated by Django 5.2.15 on 2026-07-03 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandlestickPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=100, verbose_name='Nome do Padrão')),
                ('timeframe', models.CharField(max_length=10, verbose_name='Timeframe')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('direction', models.CharField(choices=[('BULLISH', 'Alta'), ('BEARISH', 'Baixa'), ('NEUTRAL', 'Neutro')], max_length=10, verbose_name='Direção')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Confiança (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candlestick_patterns', to='market_data.asset', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Padrão de Candlestick',
                'verbose_name_plural': 'Padrões de Candlestick',
                'ordering': ['asset', 'timeframe', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=50, verbose_name='Nome do Indicador')),
                ('timeframe', models.CharField(max_length=10, verbose_name='Timeframe')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('values', models.JSONField(verbose_name='Valores')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_indicators', to='market_data.asset', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Indicador Técnico',
                'verbose_name_plural': 'Indicadores Técnicos',
                'ordering': ['asset', 'indicator_name', 'timeframe', '-timestamp'],
            },
        ),
    ]
