# Generated by Django 5.2.15 on 2026-07-03 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('BULLISH', 'Alta'), ('BEARISH', 'Baixa'), ('NEUTRAL', 'Neutro')], max_length=10, verbose_name='Tipo de Sinal')),
                ('confidence_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Confiança (%)')),
                ('technical_justification', models.TextField(verbose_name='Justificativa Técnica')),
                ('fundamental_justification', models.TextField(blank=True, verbose_name='Justificativa Fundamentalista')),
                ('macro_justification', models.TextField(verbose_name='Justificativa Macroeconômica')),
                ('synthesis_text', models.TextField(verbose_name='Síntese')),
                ('timeframe', models.CharField(max_length=10, verbose_name='Timeframe')),
                ('generated_at', models.DateTimeField(verbose_name='Gerado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_signals', to='market_data.asset', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sinal de IA',
                'verbose_name_plural': 'Sinais de IA',
                'ordering': ['-generated_at'],
            },
        ),
    ]
