# Generated by Django 5.2.15 on 2026-07-03 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100, verbose_name='Nome da Estratégia')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Capital Inicial (R$)')),
                ('final_capital', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Capital Final (R$)')),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Acerto (%)')),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Índice de Sharpe')),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Drawdown Máximo (%)')),
                ('trades_log', models.JSONField(default=list, verbose_name='Log de Trades')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_results', to='market_data.asset', verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_results', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resultado de Backtest',
                'verbose_name_plural': 'Resultados de Backtest',
                'ordering': ['-created_at'],
            },
        ),
    ]
